name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: echo "GIT_COMMIT=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
      - run: echo "GIT_TAG=`echo $(git describe --tags --exact-match ${{ env.GIT_COMMIT }} || :)`" >> $GITHUB_ENV
      - run: echo ${{ env.GIT_TAG }} != v*
      - name: Run external sh for testing
        run: |
         sh ./scripts/publish.sh    
      - run: |
          if [[ ${{ env.GIT_TAG }} == v* ]] ; then
          echo "Tag found..."
          else
          echo "No git tag found, action cancelled..."
          exit 1
          fi


      - uses: andymckay/cancel-action@0.2
        if: ${{ env.GIT_TAG }} != v*
          
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
