name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "GIT_COMMIT=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
      - run: echo "GIT_TAG=`echo $(git describe --tags --exact-match ${{ env.GIT_COMMIT }} || :)`" >> $GITHUB_ENV
      - uses: andymckay/cancel-action@0.2
        if: startsWith(${{ env.GIT_TAG }}, 'v')
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/     
          
      - run: npm install
      - run: npm publish --access public
        if: startsWith(${{ env.GIT_TAG }}, 'v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
