name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/     
      - run: echo "GIT_COMMIT=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
      - run: echo "GIT_TAG=`echo $(git describe --tags --exact-match ${{ env.GIT_COMMIT }} || :)`" >> $GITHUB_ENV
      - run: |
          if msg=`git describe --exact-match --tags @ 2>&1`; then 
          echo tagged $msg; 
          else 
          echo "no git tag found" 
          fi
      - run: |
          echo "Environment variables from commit"
          echo "GIT_COMMIT-->${{ env.GIT_COMMIT }}"
          echo "GIT_TAG-->${{ env.GIT_TAG }}"
      - run: |
          if ${{ env.GIT_TAG }}==''; then
          echo "no git tag..."
          exit 1
          fi

      - uses: andymckay/cancel-action@0.2
        if: ${{ failure() }}
          
      - run: npm install
        if: ${{ success() }}
      - run: npm publish --access public
        if: ${{ success() }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
