name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/     
      - run: echo "GIT_COMMIT=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
      - run: echo "GIT_TAG=`echo $(git describe --tags --exact-match ${{ env.GIT_COMMIT }} || :)`" >> $GITHUB_ENV
      - run: |
          echo "Environment variables from commit"
          echo "GIT_COMMIT-->${{ env.GIT_COMMIT }}"
          echo "GIT_TAG-->${{ env.GIT_TAG }}"
      - run: |
          echo "github.ref: ${{ github.ref }}"
      - run: |
          if [[ ${{ env.GIT_TAG }} == v* ]] ; then
          echo "Tag found..."
          else
          echo "No git tag found, action cancelled..."
          exit 1
          fi

      - uses: andymckay/cancel-action@0.2
        if: ! startsWith(github.ref, 'refs/tags/v')
          
      - run: npm install
        if: startsWith(github.ref, 'refs/tags/v')
      - run: npm publish --access public
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
