name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/     
      - name: Get commit 
        run: echo "GIT_COMMIT=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
        if: steps.check.outputs.triggered == 'true'
      - name: Check commit tag exists or not
        run: echo "GIT_TAG=`echo $(git describe --tags --exact-match ${{ env.GIT_COMMIT }} || :)`" >> $GITHUB_ENV
        if: steps.check.outputs.triggered == 'true'
      - name: Decide that continue build or not with git tag control
      - uses: andymckay/cancel-action@0.2
        if: ${{ (steps.check.outputs.triggered == 'true') && (startsWith(${{ env.GIT_TAG }}, 'v')) }}
          
      - run: npm install
      - run: npm publish --access public
        if: startsWith(${{ env.GIT_TAG }}, 'v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
