name: NPM Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build ðŸ— & Publish ðŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/cancel-action@0.2
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/      
      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - run: echo ${{ github.ref }}
      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - run: npm install
      - run: npm publish --access public
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
